//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 22/07/2019 12:39:45
namespace Costos.Entidades
{
    
    /// <summary>
    /// No hay ningún comentario para MVI_IPModel.Mvi_cAlternativas en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cAltClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MVI_IPModel", Name="Mvi_cAlternativas")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mvi_cAlternativas : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Mvi_cAlternativas.
        /// </summary>
        /// <param name="cAltClave">Valor inicial de cAltClave.</param>
        /// <param name="cPrdModelo">Valor inicial de cPrdModelo.</param>
        /// <param name="cColClave">Valor inicial de cColClave.</param>
        /// <param name="cMatClave">Valor inicial de cMatClave.</param>
        /// <param name="cAltPrecioCompra">Valor inicial de cAltPrecioCompra.</param>
        /// <param name="cClPClave">Valor inicial de cClPClave.</param>
        /// <param name="cPrvClaveFab">Valor inicial de cPrvClaveFab.</param>
        /// <param name="cAltCostoDlls">Valor inicial de cAltCostoDlls.</param>
        /// <param name="cTiPClave">Valor inicial de cTiPClave.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Mvi_cAlternativas CreateMvi_cAlternativas(string cAltClave, int cPrdModelo, string cColClave, string cMatClave, decimal cAltPrecioCompra, byte cClPClave, string cPrvClaveFab, decimal cAltCostoDlls, byte cTiPClave)
        {
            Mvi_cAlternativas mvi_cAlternativas = new Mvi_cAlternativas();
            mvi_cAlternativas.cAltClave = cAltClave;
            mvi_cAlternativas.cPrdModelo = cPrdModelo;
            mvi_cAlternativas.cColClave = cColClave;
            mvi_cAlternativas.cMatClave = cMatClave;
            mvi_cAlternativas.cAltPrecioCompra = cAltPrecioCompra;
            mvi_cAlternativas.cClPClave = cClPClave;
            mvi_cAlternativas.cPrvClaveFab = cPrvClaveFab;
            mvi_cAlternativas.cAltCostoDlls = cAltCostoDlls;
            mvi_cAlternativas.cTiPClave = cTiPClave;
            return mvi_cAlternativas;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cAltClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cAltClave
        {
            get
            {
                return this._cAltClave;
            }
            set
            {
                this.OncAltClaveChanging(value);
                this.ReportPropertyChanging("cAltClave");
                this._cAltClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cAltClave");
                this.OncAltClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cAltClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltClaveChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cPrdModelo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cPrdModelo
        {
            get
            {
                return this._cPrdModelo;
            }
            set
            {
                this.OncPrdModeloChanging(value);
                this.ReportPropertyChanging("cPrdModelo");
                this._cPrdModelo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cPrdModelo");
                this.OncPrdModeloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cPrdModelo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncPrdModeloChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncPrdModeloChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cColClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cColClave
        {
            get
            {
                return this._cColClave;
            }
            set
            {
                this.OncColClaveChanging(value);
                this.ReportPropertyChanging("cColClave");
                this._cColClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cColClave");
                this.OncColClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cColClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncColClaveChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncColClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cMatClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cMatClave
        {
            get
            {
                return this._cMatClave;
            }
            set
            {
                this.OncMatClaveChanging(value);
                this.ReportPropertyChanging("cMatClave");
                this._cMatClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cMatClave");
                this.OncMatClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cMatClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncMatClaveChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncMatClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAltPrecioCompra en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal cAltPrecioCompra
        {
            get
            {
                return this._cAltPrecioCompra;
            }
            set
            {
                this.OncAltPrecioCompraChanging(value);
                this.ReportPropertyChanging("cAltPrecioCompra");
                this._cAltPrecioCompra = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAltPrecioCompra");
                this.OncAltPrecioCompraChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _cAltPrecioCompra;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltPrecioCompraChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltPrecioCompraChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cClPClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte cClPClave
        {
            get
            {
                return this._cClPClave;
            }
            set
            {
                this.OncClPClaveChanging(value);
                this.ReportPropertyChanging("cClPClave");
                this._cClPClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cClPClave");
                this.OncClPClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _cClPClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncClPClaveChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncClPClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cPrvClaveFab en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cPrvClaveFab
        {
            get
            {
                return this._cPrvClaveFab;
            }
            set
            {
                this.OncPrvClaveFabChanging(value);
                this.ReportPropertyChanging("cPrvClaveFab");
                this._cPrvClaveFab = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cPrvClaveFab");
                this.OncPrvClaveFabChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cPrvClaveFab;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncPrvClaveFabChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncPrvClaveFabChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAltCostoDlls en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal cAltCostoDlls
        {
            get
            {
                return this._cAltCostoDlls;
            }
            set
            {
                this.OncAltCostoDllsChanging(value);
                this.ReportPropertyChanging("cAltCostoDlls");
                this._cAltCostoDlls = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAltCostoDlls");
                this.OncAltCostoDllsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _cAltCostoDlls;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltCostoDllsChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltCostoDllsChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTiPClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte cTiPClave
        {
            get
            {
                return this._cTiPClave;
            }
            set
            {
                this.OncTiPClaveChanging(value);
                this.ReportPropertyChanging("cTiPClave");
                this._cTiPClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTiPClave");
                this.OncTiPClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _cTiPClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPClaveChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPClaveChanged();
    }
    /// <summary>
    /// No hay ningún comentario para MVI_IPModel.Mvi_cCalendario en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cCalClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MVI_IPModel", Name="Mvi_cCalendario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mvi_cCalendario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Mvi_cCalendario.
        /// </summary>
        /// <param name="cCalClave">Valor inicial de cCalClave.</param>
        /// <param name="cCalNoSemana">Valor inicial de cCalNoSemana.</param>
        /// <param name="cCalAnio">Valor inicial de cCalAnio.</param>
        /// <param name="cCalFechaInicio">Valor inicial de cCalFechaInicio.</param>
        /// <param name="cCalFechaFinal">Valor inicial de cCalFechaFinal.</param>
        /// <param name="cCalMes">Valor inicial de cCalMes.</param>
        /// <param name="cCalProcesada">Valor inicial de cCalProcesada.</param>
        /// <param name="cCalExportada">Valor inicial de cCalExportada.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Mvi_cCalendario CreateMvi_cCalendario(int cCalClave, int cCalNoSemana, int cCalAnio, global::System.DateTime cCalFechaInicio, global::System.DateTime cCalFechaFinal, int cCalMes, bool cCalProcesada, bool cCalExportada)
        {
            Mvi_cCalendario mvi_cCalendario = new Mvi_cCalendario();
            mvi_cCalendario.cCalClave = cCalClave;
            mvi_cCalendario.cCalNoSemana = cCalNoSemana;
            mvi_cCalendario.cCalAnio = cCalAnio;
            mvi_cCalendario.cCalFechaInicio = cCalFechaInicio;
            mvi_cCalendario.cCalFechaFinal = cCalFechaFinal;
            mvi_cCalendario.cCalMes = cCalMes;
            mvi_cCalendario.cCalProcesada = cCalProcesada;
            mvi_cCalendario.cCalExportada = cCalExportada;
            return mvi_cCalendario;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cCalClave
        {
            get
            {
                return this._cCalClave;
            }
            set
            {
                this.OncCalClaveChanging(value);
                this.ReportPropertyChanging("cCalClave");
                this._cCalClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalClave");
                this.OncCalClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cCalClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalClaveChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalNoSemana en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cCalNoSemana
        {
            get
            {
                return this._cCalNoSemana;
            }
            set
            {
                this.OncCalNoSemanaChanging(value);
                this.ReportPropertyChanging("cCalNoSemana");
                this._cCalNoSemana = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalNoSemana");
                this.OncCalNoSemanaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cCalNoSemana;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalNoSemanaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalNoSemanaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalAnio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cCalAnio
        {
            get
            {
                return this._cCalAnio;
            }
            set
            {
                this.OncCalAnioChanging(value);
                this.ReportPropertyChanging("cCalAnio");
                this._cCalAnio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalAnio");
                this.OncCalAnioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cCalAnio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalAnioChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalAnioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalFechaInicio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime cCalFechaInicio
        {
            get
            {
                return this._cCalFechaInicio;
            }
            set
            {
                this.OncCalFechaInicioChanging(value);
                this.ReportPropertyChanging("cCalFechaInicio");
                this._cCalFechaInicio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalFechaInicio");
                this.OncCalFechaInicioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _cCalFechaInicio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalFechaInicioChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalFechaInicioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalFechaFinal en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime cCalFechaFinal
        {
            get
            {
                return this._cCalFechaFinal;
            }
            set
            {
                this.OncCalFechaFinalChanging(value);
                this.ReportPropertyChanging("cCalFechaFinal");
                this._cCalFechaFinal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalFechaFinal");
                this.OncCalFechaFinalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _cCalFechaFinal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalFechaFinalChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalFechaFinalChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalMes en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cCalMes
        {
            get
            {
                return this._cCalMes;
            }
            set
            {
                this.OncCalMesChanging(value);
                this.ReportPropertyChanging("cCalMes");
                this._cCalMes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalMes");
                this.OncCalMesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cCalMes;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalMesChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalMesChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalProcesada en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool cCalProcesada
        {
            get
            {
                return this._cCalProcesada;
            }
            set
            {
                this.OncCalProcesadaChanging(value);
                this.ReportPropertyChanging("cCalProcesada");
                this._cCalProcesada = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalProcesada");
                this.OncCalProcesadaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _cCalProcesada;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalProcesadaChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalProcesadaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cCalExportada en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool cCalExportada
        {
            get
            {
                return this._cCalExportada;
            }
            set
            {
                this.OncCalExportadaChanging(value);
                this.ReportPropertyChanging("cCalExportada");
                this._cCalExportada = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cCalExportada");
                this.OncCalExportadaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _cCalExportada;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalExportadaChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncCalExportadaChanged();
    }
    /// <summary>
    /// No hay ningún comentario para MVI_IPEntities en el esquema.
    /// </summary>
    public partial class MVI_IPEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto MVI_IPEntities usando la cadena de conexión encontrada en la sección 'MVI_IPEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public MVI_IPEntities() : 
                base("name=MVI_IPEntities", "MVI_IPEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto MVI_IPEntities.
        /// </summary>
        public MVI_IPEntities(string connectionString) : 
                base(connectionString, "MVI_IPEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto MVI_IPEntities.
        /// </summary>
        public MVI_IPEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MVI_IPEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Mvi_cAlternativas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Mvi_cAlternativas> Mvi_cAlternativas
        {
            get
            {
                if ((this._Mvi_cAlternativas == null))
                {
                    this._Mvi_cAlternativas = base.CreateQuery<Mvi_cAlternativas>("[Mvi_cAlternativas]");
                }
                return this._Mvi_cAlternativas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Mvi_cAlternativas> _Mvi_cAlternativas;
        /// <summary>
        /// No hay ningún comentario para Mvi_cCalendario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Mvi_cCalendario> Mvi_cCalendario
        {
            get
            {
                if ((this._Mvi_cCalendario == null))
                {
                    this._Mvi_cCalendario = base.CreateQuery<Mvi_cCalendario>("[Mvi_cCalendario]");
                }
                return this._Mvi_cCalendario;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Mvi_cCalendario> _Mvi_cCalendario;
        /// <summary>
        /// No hay ningún comentario para Mvi_cTiposProducto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Mvi_cTiposProducto> Mvi_cTiposProducto
        {
            get
            {
                if ((this._Mvi_cTiposProducto == null))
                {
                    this._Mvi_cTiposProducto = base.CreateQuery<Mvi_cTiposProducto>("[Mvi_cTiposProducto]");
                }
                return this._Mvi_cTiposProducto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Mvi_cTiposProducto> _Mvi_cTiposProducto;
        /// <summary>
        /// No hay ningún comentario para Mvi_cAlternativas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMvi_cAlternativas(Mvi_cAlternativas mvi_cAlternativas)
        {
            base.AddObject("Mvi_cAlternativas", mvi_cAlternativas);
        }
        /// <summary>
        /// No hay ningún comentario para Mvi_cCalendario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMvi_cCalendario(Mvi_cCalendario mvi_cCalendario)
        {
            base.AddObject("Mvi_cCalendario", mvi_cCalendario);
        }
        /// <summary>
        /// No hay ningún comentario para Mvi_cTiposProducto en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToMvi_cTiposProducto(Mvi_cTiposProducto mvi_cTiposProducto)
        {
            base.AddObject("Mvi_cTiposProducto", mvi_cTiposProducto);
        }
    }
    /// <summary>
    /// No hay ningún comentario para MVI_IPModel.Mvi_cTiposProducto en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cTiPClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MVI_IPModel", Name="Mvi_cTiposProducto")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mvi_cTiposProducto : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Mvi_cTiposProducto.
        /// </summary>
        /// <param name="cTiPClave">Valor inicial de cTiPClave.</param>
        /// <param name="cTiPNombre">Valor inicial de cTiPNombre.</param>
        /// <param name="cTiPActivo">Valor inicial de cTiPActivo.</param>
        /// <param name="cClPClave">Valor inicial de cClPClave.</param>
        /// <param name="cTipGenero">Valor inicial de cTipGenero.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Mvi_cTiposProducto CreateMvi_cTiposProducto(byte cTiPClave, string cTiPNombre, bool cTiPActivo, byte cClPClave, byte cTipGenero)
        {
            Mvi_cTiposProducto mvi_cTiposProducto = new Mvi_cTiposProducto();
            mvi_cTiposProducto.cTiPClave = cTiPClave;
            mvi_cTiposProducto.cTiPNombre = cTiPNombre;
            mvi_cTiposProducto.cTiPActivo = cTiPActivo;
            mvi_cTiposProducto.cClPClave = cClPClave;
            mvi_cTiposProducto.cTipGenero = cTipGenero;
            return mvi_cTiposProducto;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cTiPClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte cTiPClave
        {
            get
            {
                return this._cTiPClave;
            }
            set
            {
                this.OncTiPClaveChanging(value);
                this.ReportPropertyChanging("cTiPClave");
                this._cTiPClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTiPClave");
                this.OncTiPClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _cTiPClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPClaveChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTiPNombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cTiPNombre
        {
            get
            {
                return this._cTiPNombre;
            }
            set
            {
                this.OncTiPNombreChanging(value);
                this.ReportPropertyChanging("cTiPNombre");
                this._cTiPNombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cTiPNombre");
                this.OncTiPNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cTiPNombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTiPActivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool cTiPActivo
        {
            get
            {
                return this._cTiPActivo;
            }
            set
            {
                this.OncTiPActivoChanging(value);
                this.ReportPropertyChanging("cTiPActivo");
                this._cTiPActivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTiPActivo");
                this.OncTiPActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _cTiPActivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTiPActivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cClPClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte cClPClave
        {
            get
            {
                return this._cClPClave;
            }
            set
            {
                this.OncClPClaveChanging(value);
                this.ReportPropertyChanging("cClPClave");
                this._cClPClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cClPClave");
                this.OncClPClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _cClPClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncClPClaveChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncClPClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTipGenero en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte cTipGenero
        {
            get
            {
                return this._cTipGenero;
            }
            set
            {
                this.OncTipGeneroChanging(value);
                this.ReportPropertyChanging("cTipGenero");
                this._cTipGenero = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTipGenero");
                this.OncTipGeneroChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _cTipGenero;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTipGeneroChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTipGeneroChanged();
    }
}
