//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 25/04/2019 10:58:01 a. m.
namespace Transito.Entidades
{
    
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_cAlmacenes en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// CAlmClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_cAlmacenes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_cAlmacenes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_cAlmacenes.
        /// </summary>
        /// <param name="cAlmClave">Valor inicial de CAlmClave.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_cAlmacenes CreateSvp_cAlmacenes(short cAlmClave)
        {
            Svp_cAlmacenes svp_cAlmacenes = new Svp_cAlmacenes();
            svp_cAlmacenes.CAlmClave = cAlmClave;
            return svp_cAlmacenes;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad CAlmClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short CAlmClave
        {
            get
            {
                return this._CAlmClave;
            }
            set
            {
                this.OnCAlmClaveChanging(value);
                this.ReportPropertyChanging("CAlmClave");
                this._CAlmClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CAlmClave");
                this.OnCAlmClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _CAlmClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCAlmClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCAlmClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad CUdNContabilidad en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CUdNContabilidad
        {
            get
            {
                return this._CUdNContabilidad;
            }
            set
            {
                this.OnCUdNContabilidadChanging(value);
                this.ReportPropertyChanging("CUdNContabilidad");
                this._CUdNContabilidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CUdNContabilidad");
                this.OnCUdNContabilidadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CUdNContabilidad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCUdNContabilidadChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCUdNContabilidadChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad CAlmNombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CAlmNombre
        {
            get
            {
                return this._CAlmNombre;
            }
            set
            {
                this.OnCAlmNombreChanging(value);
                this.ReportPropertyChanging("CAlmNombre");
                this._CAlmNombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CAlmNombre");
                this.OnCAlmNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CAlmNombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCAlmNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCAlmNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmPrefijoSIA en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cAlmPrefijoSIA
        {
            get
            {
                return this._cAlmPrefijoSIA;
            }
            set
            {
                this.OncAlmPrefijoSIAChanging(value);
                this.ReportPropertyChanging("cAlmPrefijoSIA");
                this._cAlmPrefijoSIA = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cAlmPrefijoSIA");
                this.OncAlmPrefijoSIAChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cAlmPrefijoSIA;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmPrefijoSIAChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmPrefijoSIAChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmIPServidor en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cAlmIPServidor
        {
            get
            {
                return this._cAlmIPServidor;
            }
            set
            {
                this.OncAlmIPServidorChanging(value);
                this.ReportPropertyChanging("cAlmIPServidor");
                this._cAlmIPServidor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cAlmIPServidor");
                this.OncAlmIPServidorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cAlmIPServidor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmIPServidorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmIPServidorChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmActivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> cAlmActivo
        {
            get
            {
                return this._cAlmActivo;
            }
            set
            {
                this.OncAlmActivoChanging(value);
                this.ReportPropertyChanging("cAlmActivo");
                this._cAlmActivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmActivo");
                this.OncAlmActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _cAlmActivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmActivoChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmActivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cUniversal en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> cUniversal
        {
            get
            {
                return this._cUniversal;
            }
            set
            {
                this.OncUniversalChanging(value);
                this.ReportPropertyChanging("cUniversal");
                this._cUniversal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cUniversal");
                this.OncUniversalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _cUniversal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUniversalChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUniversalChanged();
    }
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_cProyectos en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cProClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_cProyectos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_cProyectos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_cProyectos.
        /// </summary>
        /// <param name="cProClave">Valor inicial de cProClave.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_cProyectos CreateSvp_cProyectos(short cProClave)
        {
            Svp_cProyectos svp_cProyectos = new Svp_cProyectos();
            svp_cProyectos.cProClave = cProClave;
            return svp_cProyectos;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cProClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cProClave
        {
            get
            {
                return this._cProClave;
            }
            set
            {
                this.OncProClaveChanging(value);
                this.ReportPropertyChanging("cProClave");
                this._cProClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cProClave");
                this.OncProClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cProClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cProNombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cProNombre
        {
            get
            {
                return this._cProNombre;
            }
            set
            {
                this.OncProNombreChanging(value);
                this.ReportPropertyChanging("cProNombre");
                this._cProNombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cProNombre");
                this.OncProNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cProNombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cProFechade en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> cProFechade
        {
            get
            {
                return this._cProFechade;
            }
            set
            {
                this.OncProFechadeChanging(value);
                this.ReportPropertyChanging("cProFechade");
                this._cProFechade = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cProFechade");
                this.OncProFechadeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _cProFechade;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProFechadeChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProFechadeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cProFechaha en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> cProFechaha
        {
            get
            {
                return this._cProFechaha;
            }
            set
            {
                this.OncProFechahaChanging(value);
                this.ReportPropertyChanging("cProFechaha");
                this._cProFechaha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cProFechaha");
                this.OncProFechahaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _cProFechaha;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProFechahaChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProFechahaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Observaciones en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Observaciones
        {
            get
            {
                return this._Observaciones;
            }
            set
            {
                this.OnObservacionesChanging(value);
                this.ReportPropertyChanging("Observaciones");
                this._Observaciones = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Observaciones");
                this.OnObservacionesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Observaciones;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObservacionesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObservacionesChanged();
    }
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_CTransito en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cTranClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_CTransito")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_CTransito : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_CTransito.
        /// </summary>
        /// <param name="cTranClave">Valor inicial de cTranClave.</param>
        /// <param name="cTranTipo">Valor inicial de cTranTipo.</param>
        /// <param name="cTranActivo">Valor inicial de CTranActivo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_CTransito CreateSvp_CTransito(short cTranClave, bool cTranTipo, bool cTranActivo)
        {
            Svp_CTransito svp_CTransito = new Svp_CTransito();
            svp_CTransito.cTranClave = cTranClave;
            svp_CTransito.cTranTipo = cTranTipo;
            svp_CTransito.CTranActivo = cTranActivo;
            return svp_CTransito;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cTranClave
        {
            get
            {
                return this._cTranClave;
            }
            set
            {
                this.OncTranClaveChanging(value);
                this.ReportPropertyChanging("cTranClave");
                this._cTranClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTranClave");
                this.OncTranClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cTranClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranNombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cTranNombre
        {
            get
            {
                return this._cTranNombre;
            }
            set
            {
                this.OncTranNombreChanging(value);
                this.ReportPropertyChanging("cTranNombre");
                this._cTranNombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cTranNombre");
                this.OncTranNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cTranNombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranTipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool cTranTipo
        {
            get
            {
                return this._cTranTipo;
            }
            set
            {
                this.OncTranTipoChanging(value);
                this.ReportPropertyChanging("cTranTipo");
                this._cTranTipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTranTipo");
                this.OncTranTipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _cTranTipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranTipoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranTipoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad CTranActivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool CTranActivo
        {
            get
            {
                return this._CTranActivo;
            }
            set
            {
                this.OnCTranActivoChanging(value);
                this.ReportPropertyChanging("CTranActivo");
                this._CTranActivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CTranActivo");
                this.OnCTranActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _CTranActivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCTranActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCTranActivoChanged();
    }
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_rTransitosxAlmacen en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_rTransitosxAlmacen")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_rTransitosxAlmacen : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_rTransitosxAlmacen.
        /// </summary>
        /// <param name="cAlmClave">Valor inicial de cAlmClave.</param>
        /// <param name="cTranClave">Valor inicial de cTranClave.</param>
        /// <param name="id">Valor inicial de id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_rTransitosxAlmacen CreateSvp_rTransitosxAlmacen(short cAlmClave, short cTranClave, int id)
        {
            Svp_rTransitosxAlmacen svp_rTransitosxAlmacen = new Svp_rTransitosxAlmacen();
            svp_rTransitosxAlmacen.cAlmClave = cAlmClave;
            svp_rTransitosxAlmacen.cTranClave = cTranClave;
            svp_rTransitosxAlmacen.id = id;
            return svp_rTransitosxAlmacen;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cAlmClave
        {
            get
            {
                return this._cAlmClave;
            }
            set
            {
                this.OncAlmClaveChanging(value);
                this.ReportPropertyChanging("cAlmClave");
                this._cAlmClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmClave");
                this.OncAlmClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cAlmClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cTranClave
        {
            get
            {
                return this._cTranClave;
            }
            set
            {
                this.OncTranClaveChanging(value);
                this.ReportPropertyChanging("cTranClave");
                this._cTranClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTranClave");
                this.OncTranClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cTranClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad rMxASQL en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string rMxASQL
        {
            get
            {
                return this._rMxASQL;
            }
            set
            {
                this.OnrMxASQLChanging(value);
                this.ReportPropertyChanging("rMxASQL");
                this._rMxASQL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("rMxASQL");
                this.OnrMxASQLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _rMxASQL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxASQLChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxASQLChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad rMxAPrefijoFehca en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string rMxAPrefijoFehca
        {
            get
            {
                return this._rMxAPrefijoFehca;
            }
            set
            {
                this.OnrMxAPrefijoFehcaChanging(value);
                this.ReportPropertyChanging("rMxAPrefijoFehca");
                this._rMxAPrefijoFehca = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("rMxAPrefijoFehca");
                this.OnrMxAPrefijoFehcaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _rMxAPrefijoFehca;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxAPrefijoFehcaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxAPrefijoFehcaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad rMxUActivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> rMxUActivo
        {
            get
            {
                return this._rMxUActivo;
            }
            set
            {
                this.OnrMxUActivoChanging(value);
                this.ReportPropertyChanging("rMxUActivo");
                this._rMxUActivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rMxUActivo");
                this.OnrMxUActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _rMxUActivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxUActivoChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnrMxUActivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChanged();
    }
    /// <summary>
    /// No hay ningún comentario para TransitosEntities en el esquema.
    /// </summary>
    public partial class TransitosEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto TransitosEntities usando la cadena de conexión encontrada en la sección 'TransitosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TransitosEntities() : 
                base("name=TransitosEntities", "TransitosEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto TransitosEntities.
        /// </summary>
        public TransitosEntities(string connectionString) : 
                base(connectionString, "TransitosEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto TransitosEntities.
        /// </summary>
        public TransitosEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TransitosEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Svp_cAlmacenes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_cAlmacenes> Svp_cAlmacenes
        {
            get
            {
                if ((this._Svp_cAlmacenes == null))
                {
                    this._Svp_cAlmacenes = base.CreateQuery<Svp_cAlmacenes>("[Svp_cAlmacenes]");
                }
                return this._Svp_cAlmacenes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_cAlmacenes> _Svp_cAlmacenes;
        /// <summary>
        /// No hay ningún comentario para Svp_cProyectos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_cProyectos> Svp_cProyectos
        {
            get
            {
                if ((this._Svp_cProyectos == null))
                {
                    this._Svp_cProyectos = base.CreateQuery<Svp_cProyectos>("[Svp_cProyectos]");
                }
                return this._Svp_cProyectos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_cProyectos> _Svp_cProyectos;
        /// <summary>
        /// No hay ningún comentario para Svp_CTransito en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_CTransito> Svp_CTransito
        {
            get
            {
                if ((this._Svp_CTransito == null))
                {
                    this._Svp_CTransito = base.CreateQuery<Svp_CTransito>("[Svp_CTransito]");
                }
                return this._Svp_CTransito;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_CTransito> _Svp_CTransito;
        /// <summary>
        /// No hay ningún comentario para Svp_rTransitosxAlmacen en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_rTransitosxAlmacen> Svp_rTransitosxAlmacen
        {
            get
            {
                if ((this._Svp_rTransitosxAlmacen == null))
                {
                    this._Svp_rTransitosxAlmacen = base.CreateQuery<Svp_rTransitosxAlmacen>("[Svp_rTransitosxAlmacen]");
                }
                return this._Svp_rTransitosxAlmacen;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_rTransitosxAlmacen> _Svp_rTransitosxAlmacen;
        /// <summary>
        /// No hay ningún comentario para Svp_TransitosTemp en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_TransitosTemp> Svp_TransitosTemp
        {
            get
            {
                if ((this._Svp_TransitosTemp == null))
                {
                    this._Svp_TransitosTemp = base.CreateQuery<Svp_TransitosTemp>("[Svp_TransitosTemp]");
                }
                return this._Svp_TransitosTemp;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_TransitosTemp> _Svp_TransitosTemp;
        /// <summary>
        /// No hay ningún comentario para Svp_DTransitos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Svp_DTransitos> Svp_DTransitos
        {
            get
            {
                if ((this._Svp_DTransitos == null))
                {
                    this._Svp_DTransitos = base.CreateQuery<Svp_DTransitos>("[Svp_DTransitos]");
                }
                return this._Svp_DTransitos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Svp_DTransitos> _Svp_DTransitos;
        /// <summary>
        /// No hay ningún comentario para Svp_cAlmacenes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_cAlmacenes(Svp_cAlmacenes svp_cAlmacenes)
        {
            base.AddObject("Svp_cAlmacenes", svp_cAlmacenes);
        }
        /// <summary>
        /// No hay ningún comentario para Svp_cProyectos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_cProyectos(Svp_cProyectos svp_cProyectos)
        {
            base.AddObject("Svp_cProyectos", svp_cProyectos);
        }
        /// <summary>
        /// No hay ningún comentario para Svp_CTransito en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_CTransito(Svp_CTransito svp_CTransito)
        {
            base.AddObject("Svp_CTransito", svp_CTransito);
        }
        /// <summary>
        /// No hay ningún comentario para Svp_rTransitosxAlmacen en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_rTransitosxAlmacen(Svp_rTransitosxAlmacen svp_rTransitosxAlmacen)
        {
            base.AddObject("Svp_rTransitosxAlmacen", svp_rTransitosxAlmacen);
        }
        /// <summary>
        /// No hay ningún comentario para Svp_TransitosTemp en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_TransitosTemp(Svp_TransitosTemp svp_TransitosTemp)
        {
            base.AddObject("Svp_TransitosTemp", svp_TransitosTemp);
        }
        /// <summary>
        /// No hay ningún comentario para Svp_DTransitos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSvp_DTransitos(Svp_DTransitos svp_DTransitos)
        {
            base.AddObject("Svp_DTransitos", svp_DTransitos);
        }
    }
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_TransitosTemp en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// mSvpFolio
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_TransitosTemp")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_TransitosTemp : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_TransitosTemp.
        /// </summary>
        /// <param name="mSvpFolio">Valor inicial de mSvpFolio.</param>
        /// <param name="cAlmClaveO">Valor inicial de cAlmClaveO.</param>
        /// <param name="cTranClave">Valor inicial de cTranClave.</param>
        /// <param name="cAlmClaveD">Valor inicial de cAlmClaveD.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_TransitosTemp CreateSvp_TransitosTemp(long mSvpFolio, short cAlmClaveO, short cTranClave, short cAlmClaveD)
        {
            Svp_TransitosTemp svp_TransitosTemp = new Svp_TransitosTemp();
            svp_TransitosTemp.mSvpFolio = mSvpFolio;
            svp_TransitosTemp.cAlmClaveO = cAlmClaveO;
            svp_TransitosTemp.cTranClave = cTranClave;
            svp_TransitosTemp.cAlmClaveD = cAlmClaveD;
            return svp_TransitosTemp;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFolio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long mSvpFolio
        {
            get
            {
                return this._mSvpFolio;
            }
            set
            {
                this.OnmSvpFolioChanging(value);
                this.ReportPropertyChanging("mSvpFolio");
                this._mSvpFolio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mSvpFolio");
                this.OnmSvpFolioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _mSvpFolio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad SvpFolioAlmacen en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<long> SvpFolioAlmacen
        {
            get
            {
                return this._SvpFolioAlmacen;
            }
            set
            {
                this.OnSvpFolioAlmacenChanging(value);
                this.ReportPropertyChanging("SvpFolioAlmacen");
                this._SvpFolioAlmacen = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SvpFolioAlmacen");
                this.OnSvpFolioAlmacenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<long> _SvpFolioAlmacen;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSvpFolioAlmacenChanging(global::System.Nullable<long> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSvpFolioAlmacenChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmClaveO en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cAlmClaveO
        {
            get
            {
                return this._cAlmClaveO;
            }
            set
            {
                this.OncAlmClaveOChanging(value);
                this.ReportPropertyChanging("cAlmClaveO");
                this._cAlmClaveO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmClaveO");
                this.OncAlmClaveOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cAlmClaveO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveOChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveOChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cTranClave
        {
            get
            {
                return this._cTranClave;
            }
            set
            {
                this.OncTranClaveChanging(value);
                this.ReportPropertyChanging("cTranClave");
                this._cTranClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTranClave");
                this.OncTranClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cTranClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFechaFolio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> mSvpFechaFolio
        {
            get
            {
                return this._mSvpFechaFolio;
            }
            set
            {
                this.OnmSvpFechaFolioChanging(value);
                this.ReportPropertyChanging("mSvpFechaFolio");
                this._mSvpFechaFolio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mSvpFechaFolio");
                this.OnmSvpFechaFolioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _mSvpFechaFolio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFechaFolioChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFechaFolioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpReferencia en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mSvpReferencia
        {
            get
            {
                return this._mSvpReferencia;
            }
            set
            {
                this.OnmSvpReferenciaChanging(value);
                this.ReportPropertyChanging("mSvpReferencia");
                this._mSvpReferencia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mSvpReferencia");
                this.OnmSvpReferenciaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mSvpReferencia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpReferenciaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpReferenciaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpObservaciones en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mSvpObservaciones
        {
            get
            {
                return this._mSvpObservaciones;
            }
            set
            {
                this.OnmSvpObservacionesChanging(value);
                this.ReportPropertyChanging("mSvpObservaciones");
                this._mSvpObservaciones = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mSvpObservaciones");
                this.OnmSvpObservacionesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mSvpObservaciones;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpObservacionesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpObservacionesChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmClaveD en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cAlmClaveD
        {
            get
            {
                return this._cAlmClaveD;
            }
            set
            {
                this.OncAlmClaveDChanging(value);
                this.ReportPropertyChanging("cAlmClaveD");
                this._cAlmClaveD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmClaveD");
                this.OncAlmClaveDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cAlmClaveD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveDChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveDChanged();
    }
    /// <summary>
    /// No hay ningún comentario para TransitosModel.Svp_DTransitos en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// mSvpFolioD
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TransitosModel", Name="Svp_DTransitos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Svp_DTransitos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Svp_DTransitos.
        /// </summary>
        /// <param name="mSvpFolio">Valor inicial de mSvpFolio.</param>
        /// <param name="mSvpFolioD">Valor inicial de mSvpFolioD.</param>
        /// <param name="mSvpFolioAlmacen">Valor inicial de mSvpFolioAlmacen.</param>
        /// <param name="cAlmClaveO">Valor inicial de cAlmClaveO.</param>
        /// <param name="cTranClave">Valor inicial de cTranClave.</param>
        /// <param name="cAlmClaveD">Valor inicial de cAlmClaveD.</param>
        /// <param name="cAltClave">Valor inicial de cAltClave.</param>
        /// <param name="cProClave">Valor inicial de cProClave.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Svp_DTransitos CreateSvp_DTransitos(long mSvpFolio, long mSvpFolioD, string mSvpFolioAlmacen, short cAlmClaveO, short cTranClave, short cAlmClaveD, string cAltClave, short cProClave)
        {
            Svp_DTransitos svp_DTransitos = new Svp_DTransitos();
            svp_DTransitos.mSvpFolio = mSvpFolio;
            svp_DTransitos.mSvpFolioD = mSvpFolioD;
            svp_DTransitos.mSvpFolioAlmacen = mSvpFolioAlmacen;
            svp_DTransitos.cAlmClaveO = cAlmClaveO;
            svp_DTransitos.cTranClave = cTranClave;
            svp_DTransitos.cAlmClaveD = cAlmClaveD;
            svp_DTransitos.cAltClave = cAltClave;
            svp_DTransitos.cProClave = cProClave;
            return svp_DTransitos;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFolio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long mSvpFolio
        {
            get
            {
                return this._mSvpFolio;
            }
            set
            {
                this.OnmSvpFolioChanging(value);
                this.ReportPropertyChanging("mSvpFolio");
                this._mSvpFolio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mSvpFolio");
                this.OnmSvpFolioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _mSvpFolio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFolioD en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long mSvpFolioD
        {
            get
            {
                return this._mSvpFolioD;
            }
            set
            {
                this.OnmSvpFolioDChanging(value);
                this.ReportPropertyChanging("mSvpFolioD");
                this._mSvpFolioD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mSvpFolioD");
                this.OnmSvpFolioDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _mSvpFolioD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioDChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFolioAlmacen en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mSvpFolioAlmacen
        {
            get
            {
                return this._mSvpFolioAlmacen;
            }
            set
            {
                this.OnmSvpFolioAlmacenChanging(value);
                this.ReportPropertyChanging("mSvpFolioAlmacen");
                this._mSvpFolioAlmacen = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mSvpFolioAlmacen");
                this.OnmSvpFolioAlmacenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mSvpFolioAlmacen;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioAlmacenChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFolioAlmacenChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmClaveO en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cAlmClaveO
        {
            get
            {
                return this._cAlmClaveO;
            }
            set
            {
                this.OncAlmClaveOChanging(value);
                this.ReportPropertyChanging("cAlmClaveO");
                this._cAlmClaveO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmClaveO");
                this.OncAlmClaveOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cAlmClaveO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveOChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveOChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cTranClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cTranClave
        {
            get
            {
                return this._cTranClave;
            }
            set
            {
                this.OncTranClaveChanging(value);
                this.ReportPropertyChanging("cTranClave");
                this._cTranClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cTranClave");
                this.OncTranClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cTranClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncTranClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAlmClaveD en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cAlmClaveD
        {
            get
            {
                return this._cAlmClaveD;
            }
            set
            {
                this.OncAlmClaveDChanging(value);
                this.ReportPropertyChanging("cAlmClaveD");
                this._cAlmClaveD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cAlmClaveD");
                this.OncAlmClaveDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cAlmClaveD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveDChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAlmClaveDChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpFechaFolio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> mSvpFechaFolio
        {
            get
            {
                return this._mSvpFechaFolio;
            }
            set
            {
                this.OnmSvpFechaFolioChanging(value);
                this.ReportPropertyChanging("mSvpFechaFolio");
                this._mSvpFechaFolio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mSvpFechaFolio");
                this.OnmSvpFechaFolioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _mSvpFechaFolio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFechaFolioChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpFechaFolioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpReferencia en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mSvpReferencia
        {
            get
            {
                return this._mSvpReferencia;
            }
            set
            {
                this.OnmSvpReferenciaChanging(value);
                this.ReportPropertyChanging("mSvpReferencia");
                this._mSvpReferencia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mSvpReferencia");
                this.OnmSvpReferenciaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mSvpReferencia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpReferenciaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpReferenciaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad mSvpObservaciones en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string mSvpObservaciones
        {
            get
            {
                return this._mSvpObservaciones;
            }
            set
            {
                this.OnmSvpObservacionesChanging(value);
                this.ReportPropertyChanging("mSvpObservaciones");
                this._mSvpObservaciones = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mSvpObservaciones");
                this.OnmSvpObservacionesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _mSvpObservaciones;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpObservacionesChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnmSvpObservacionesChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cAltClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cAltClave
        {
            get
            {
                return this._cAltClave;
            }
            set
            {
                this.OncAltClaveChanging(value);
                this.ReportPropertyChanging("cAltClave");
                this._cAltClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cAltClave");
                this.OncAltClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cAltClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltClaveChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncAltClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UnidadesFolio en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<long> UnidadesFolio
        {
            get
            {
                return this._UnidadesFolio;
            }
            set
            {
                this.OnUnidadesFolioChanging(value);
                this.ReportPropertyChanging("UnidadesFolio");
                this._UnidadesFolio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UnidadesFolio");
                this.OnUnidadesFolioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<long> _UnidadesFolio;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUnidadesFolioChanging(global::System.Nullable<long> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUnidadesFolioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cProClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cProClave
        {
            get
            {
                return this._cProClave;
            }
            set
            {
                this.OncProClaveChanging(value);
                this.ReportPropertyChanging("cProClave");
                this._cProClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cProClave");
                this.OncProClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cProClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Correcto en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> Correcto
        {
            get
            {
                return this._Correcto;
            }
            set
            {
                this.OnCorrectoChanging(value);
                this.ReportPropertyChanging("Correcto");
                this._Correcto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Correcto");
                this.OnCorrectoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _Correcto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorrectoChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCorrectoChanged();
    }
}
