//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("adminpaqModel", "FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SVP.Entidades.Cfg_AtiposUsuarios), "Cfg_cModuloxUsuario", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SVP.Entidades.Cfg_cModuloxUsuario))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("adminpaqModel", "FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SVP.Entidades.Cfg_AtiposUsuarios), "Cfg_cProgramaxTipoUsuario", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SVP.Entidades.Cfg_cProgramaxTipoUsuario))]

// Nombre de archivo original:
// Fecha de generación: 29/04/2019 10:05:45 a. m.
namespace SVP.Entidades
{
    
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_AtiposUsuarios en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// causutipo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_AtiposUsuarios")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_AtiposUsuarios : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_AtiposUsuarios.
        /// </summary>
        /// <param name="causutipo">Valor inicial de causutipo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_AtiposUsuarios CreateCfg_AtiposUsuarios(short causutipo)
        {
            Cfg_AtiposUsuarios cfg_AtiposUsuarios = new Cfg_AtiposUsuarios();
            cfg_AtiposUsuarios.causutipo = causutipo;
            return cfg_AtiposUsuarios;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad causutipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short causutipo
        {
            get
            {
                return this._causutipo;
            }
            set
            {
                this.OncausutipoChanging(value);
                this.ReportPropertyChanging("causutipo");
                this._causutipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("causutipo");
                this.OncausutipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _causutipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para Cfg_cModuloxUsuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("adminpaqModel", "FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_cModuloxUsuario")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cfg_cModuloxUsuario> Cfg_cModuloxUsuario
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cfg_cModuloxUsuario>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_cModuloxUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cfg_cModuloxUsuario>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_cModuloxUsuario", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_cProgramaxTipoUsuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("adminpaqModel", "FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_cProgramaxTipoUsuario")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cfg_cProgramaxTipoUsuario> Cfg_cProgramaxTipoUsuario
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cfg_cProgramaxTipoUsuario>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_cProgramaxTipoUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cfg_cProgramaxTipoUsuario>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_cProgramaxTipoUsuario", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_cModulos en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cModulo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_cModulos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_cModulos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_cModulos.
        /// </summary>
        /// <param name="cModulo">Valor inicial de cModulo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_cModulos CreateCfg_cModulos(short cModulo)
        {
            Cfg_cModulos cfg_cModulos = new Cfg_cModulos();
            cfg_cModulos.cModulo = cModulo;
            return cfg_cModulos;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cModulo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cModulo
        {
            get
            {
                return this._cModulo;
            }
            set
            {
                this.OncModuloChanging(value);
                this.ReportPropertyChanging("cModulo");
                this._cModulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cModulo");
                this.OncModuloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cModulo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_cModuloxUsuario en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdModxusu
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_cModuloxUsuario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_cModuloxUsuario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_cModuloxUsuario.
        /// </summary>
        /// <param name="idModxusu">Valor inicial de IdModxusu.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_cModuloxUsuario CreateCfg_cModuloxUsuario(short idModxusu)
        {
            Cfg_cModuloxUsuario cfg_cModuloxUsuario = new Cfg_cModuloxUsuario();
            cfg_cModuloxUsuario.IdModxusu = idModxusu;
            return cfg_cModuloxUsuario;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdModxusu en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short IdModxusu
        {
            get
            {
                return this._IdModxusu;
            }
            set
            {
                this.OnIdModxusuChanging(value);
                this.ReportPropertyChanging("IdModxusu");
                this._IdModxusu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdModxusu");
                this.OnIdModxusuChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _IdModxusu;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdModxusuChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdModxusuChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cModulo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> cModulo
        {
            get
            {
                return this._cModulo;
            }
            set
            {
                this.OncModuloChanging(value);
                this.ReportPropertyChanging("cModulo");
                this._cModulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cModulo");
                this.OncModuloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _cModulo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanged();
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("adminpaqModel", "FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cfg_AtiposUsuarios Cfg_AtiposUsuarios
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cfg_AtiposUsuarios> Cfg_AtiposUsuariosReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cModuloxUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_cProgramaxTipoUsuario en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// ctipoxprogramaclave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_cProgramaxTipoUsuario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_cProgramaxTipoUsuario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_cProgramaxTipoUsuario.
        /// </summary>
        /// <param name="ctipoxprogramaclave">Valor inicial de ctipoxprogramaclave.</param>
        /// <param name="cPrograma">Valor inicial de cPrograma.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_cProgramaxTipoUsuario CreateCfg_cProgramaxTipoUsuario(int ctipoxprogramaclave, int cPrograma)
        {
            Cfg_cProgramaxTipoUsuario cfg_cProgramaxTipoUsuario = new Cfg_cProgramaxTipoUsuario();
            cfg_cProgramaxTipoUsuario.ctipoxprogramaclave = ctipoxprogramaclave;
            cfg_cProgramaxTipoUsuario.cPrograma = cPrograma;
            return cfg_cProgramaxTipoUsuario;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad ctipoxprogramaclave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ctipoxprogramaclave
        {
            get
            {
                return this._ctipoxprogramaclave;
            }
            set
            {
                this.OnctipoxprogramaclaveChanging(value);
                this.ReportPropertyChanging("ctipoxprogramaclave");
                this._ctipoxprogramaclave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ctipoxprogramaclave");
                this.OnctipoxprogramaclaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ctipoxprogramaclave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnctipoxprogramaclaveChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnctipoxprogramaclaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cPrograma en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cPrograma
        {
            get
            {
                return this._cPrograma;
            }
            set
            {
                this.OncProgramaChanging(value);
                this.ReportPropertyChanging("cPrograma");
                this._cPrograma = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cPrograma");
                this.OncProgramaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cPrograma;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanged();
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("adminpaqModel", "FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cfg_AtiposUsuarios Cfg_AtiposUsuarios
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cfg_AtiposUsuarios> Cfg_AtiposUsuariosReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cfg_AtiposUsuarios>("adminpaqModel.FK_Cfg_cProgramaxTipoUsuario_Cfg_AtiposUsuarios", "Cfg_AtiposUsuarios", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_cUsuarios en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cUsuClave
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_cUsuarios")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_cUsuarios : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_cUsuarios.
        /// </summary>
        /// <param name="cUsuClave">Valor inicial de cUsuClave.</param>
        /// <param name="cUsuNombre">Valor inicial de cUsuNombre.</param>
        /// <param name="cUsucontrasena">Valor inicial de cUsucontrasena.</param>
        /// <param name="cUsuActivo">Valor inicial de cUsuActivo.</param>
        /// <param name="causutipo">Valor inicial de causutipo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_cUsuarios CreateCfg_cUsuarios(short cUsuClave, string cUsuNombre, string cUsucontrasena, bool cUsuActivo, short causutipo)
        {
            Cfg_cUsuarios cfg_cUsuarios = new Cfg_cUsuarios();
            cfg_cUsuarios.cUsuClave = cUsuClave;
            cfg_cUsuarios.cUsuNombre = cUsuNombre;
            cfg_cUsuarios.cUsucontrasena = cUsucontrasena;
            cfg_cUsuarios.cUsuActivo = cUsuActivo;
            cfg_cUsuarios.causutipo = causutipo;
            return cfg_cUsuarios;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cUsuClave en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short cUsuClave
        {
            get
            {
                return this._cUsuClave;
            }
            set
            {
                this.OncUsuClaveChanging(value);
                this.ReportPropertyChanging("cUsuClave");
                this._cUsuClave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cUsuClave");
                this.OncUsuClaveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _cUsuClave;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuClaveChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuClaveChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cUsuNombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cUsuNombre
        {
            get
            {
                return this._cUsuNombre;
            }
            set
            {
                this.OncUsuNombreChanging(value);
                this.ReportPropertyChanging("cUsuNombre");
                this._cUsuNombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cUsuNombre");
                this.OncUsuNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cUsuNombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cUsucontrasena en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string cUsucontrasena
        {
            get
            {
                return this._cUsucontrasena;
            }
            set
            {
                this.OncUsucontrasenaChanging(value);
                this.ReportPropertyChanging("cUsucontrasena");
                this._cUsucontrasena = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("cUsucontrasena");
                this.OncUsucontrasenaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _cUsucontrasena;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsucontrasenaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsucontrasenaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cUsuActivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool cUsuActivo
        {
            get
            {
                return this._cUsuActivo;
            }
            set
            {
                this.OncUsuActivoChanging(value);
                this.ReportPropertyChanging("cUsuActivo");
                this._cUsuActivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cUsuActivo");
                this.OncUsuActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _cUsuActivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncUsuActivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad causutipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short causutipo
        {
            get
            {
                return this._causutipo;
            }
            set
            {
                this.OncausutipoChanging(value);
                this.ReportPropertyChanging("causutipo");
                this._causutipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("causutipo");
                this.OncausutipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _causutipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanged();
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.Cfg_Programa en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// cPrograma
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="Cfg_Programa")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cfg_Programa : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Cfg_Programa.
        /// </summary>
        /// <param name="cPrograma">Valor inicial de cPrograma.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Cfg_Programa CreateCfg_Programa(int cPrograma)
        {
            Cfg_Programa cfg_Programa = new Cfg_Programa();
            cfg_Programa.cPrograma = cPrograma;
            return cfg_Programa;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad cPrograma en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cPrograma
        {
            get
            {
                return this._cPrograma;
            }
            set
            {
                this.OncProgramaChanging(value);
                this.ReportPropertyChanging("cPrograma");
                this._cPrograma = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cPrograma");
                this.OncProgramaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cPrograma;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.configuracion en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Idonfiguracion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="configuracion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class configuracion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto configuracion.
        /// </summary>
        /// <param name="idonfiguracion">Valor inicial de Idonfiguracion.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static configuracion Createconfiguracion(decimal idonfiguracion)
        {
            configuracion configuracion = new configuracion();
            configuracion.Idonfiguracion = idonfiguracion;
            return configuracion;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad Idonfiguracion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal Idonfiguracion
        {
            get
            {
                return this._Idonfiguracion;
            }
            set
            {
                this.OnIdonfiguracionChanging(value);
                this.ReportPropertyChanging("Idonfiguracion");
                this._Idonfiguracion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Idonfiguracion");
                this.OnIdonfiguracionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _Idonfiguracion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdonfiguracionChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdonfiguracionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaU en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaU
        {
            get
            {
                return this._FechaU;
            }
            set
            {
                this.OnFechaUChanging(value);
                this.ReportPropertyChanging("FechaU");
                this._FechaU = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaU");
                this.OnFechaUChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaU;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaUChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaUChanged();
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.LOGG en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Idlog
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="LOGG")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LOGG : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto LOGG.
        /// </summary>
        /// <param name="idlog">Valor inicial de Idlog.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static LOGG CreateLOGG(long idlog)
        {
            LOGG lOGG = new LOGG();
            lOGG.Idlog = idlog;
            return lOGG;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad Idlog en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long Idlog
        {
            get
            {
                return this._Idlog;
            }
            set
            {
                this.OnIdlogChanging(value);
                this.ReportPropertyChanging("Idlog");
                this._Idlog = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Idlog");
                this.OnIdlogChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _Idlog;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdlogChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdlogChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Modulo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Modulo
        {
            get
            {
                return this._Modulo;
            }
            set
            {
                this.OnModuloChanging(value);
                this.ReportPropertyChanging("Modulo");
                this._Modulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Modulo");
                this.OnModuloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Modulo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModuloChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnModuloChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Valor en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Valor
        {
            get
            {
                return this._Valor;
            }
            set
            {
                this.OnValorChanging(value);
                this.ReportPropertyChanging("Valor");
                this._Valor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Valor");
                this.OnValorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Valor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValorChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Mensaje en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Mensaje
        {
            get
            {
                return this._Mensaje;
            }
            set
            {
                this.OnMensajeChanging(value);
                this.ReportPropertyChanging("Mensaje");
                this._Mensaje = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Mensaje");
                this.OnMensajeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Mensaje;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMensajeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMensajeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Usuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                this.OnUsuarioChanging(value);
                this.ReportPropertyChanging("Usuario");
                this._Usuario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Usuario");
                this.OnUsuarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Usuario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Fecha en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this.ReportPropertyChanging("Fecha");
                this._Fecha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha");
                this.OnFechaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _Fecha;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad hora en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.TimeSpan> hora
        {
            get
            {
                return this._hora;
            }
            set
            {
                this.OnhoraChanging(value);
                this.ReportPropertyChanging("hora");
                this._hora = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("hora");
                this.OnhoraChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.TimeSpan> _hora;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnhoraChanging(global::System.Nullable<global::System.TimeSpan> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnhoraChanged();
    }
    /// <summary>
    /// No hay ningún comentario para UsuariosEntities en el esquema.
    /// </summary>
    public partial class UsuariosEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto UsuariosEntities usando la cadena de conexión encontrada en la sección 'UsuariosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        //public UsuariosEntities() : 
        //        base("name=UsuariosEntities", "UsuariosEntities")
        //{
        //    this.OnContextCreated();
        //}
        /// <summary>
        /// Inicializar un nuevo objeto UsuariosEntities.
        /// </summary>
        public UsuariosEntities(string connectionString) : 
                base(connectionString, "UsuariosEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto UsuariosEntities.
        /// </summary>
        public UsuariosEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "UsuariosEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_AtiposUsuarios> Cfg_AtiposUsuarios
        {
            get
            {
                if ((this._Cfg_AtiposUsuarios == null))
                {
                    this._Cfg_AtiposUsuarios = base.CreateQuery<Cfg_AtiposUsuarios>("[Cfg_AtiposUsuarios]");
                }
                return this._Cfg_AtiposUsuarios;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_AtiposUsuarios> _Cfg_AtiposUsuarios;
        /// <summary>
        /// No hay ningún comentario para Cfg_cModulos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_cModulos> Cfg_cModulos
        {
            get
            {
                if ((this._Cfg_cModulos == null))
                {
                    this._Cfg_cModulos = base.CreateQuery<Cfg_cModulos>("[Cfg_cModulos]");
                }
                return this._Cfg_cModulos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_cModulos> _Cfg_cModulos;
        /// <summary>
        /// No hay ningún comentario para Cfg_cModuloxUsuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_cModuloxUsuario> Cfg_cModuloxUsuario
        {
            get
            {
                if ((this._Cfg_cModuloxUsuario == null))
                {
                    this._Cfg_cModuloxUsuario = base.CreateQuery<Cfg_cModuloxUsuario>("[Cfg_cModuloxUsuario]");
                }
                return this._Cfg_cModuloxUsuario;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_cModuloxUsuario> _Cfg_cModuloxUsuario;
        /// <summary>
        /// No hay ningún comentario para Cfg_cProgramaxTipoUsuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_cProgramaxTipoUsuario> Cfg_cProgramaxTipoUsuario
        {
            get
            {
                if ((this._Cfg_cProgramaxTipoUsuario == null))
                {
                    this._Cfg_cProgramaxTipoUsuario = base.CreateQuery<Cfg_cProgramaxTipoUsuario>("[Cfg_cProgramaxTipoUsuario]");
                }
                return this._Cfg_cProgramaxTipoUsuario;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_cProgramaxTipoUsuario> _Cfg_cProgramaxTipoUsuario;
        /// <summary>
        /// No hay ningún comentario para Cfg_cUsuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_cUsuarios> Cfg_cUsuarios
        {
            get
            {
                if ((this._Cfg_cUsuarios == null))
                {
                    this._Cfg_cUsuarios = base.CreateQuery<Cfg_cUsuarios>("[Cfg_cUsuarios]");
                }
                return this._Cfg_cUsuarios;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_cUsuarios> _Cfg_cUsuarios;
        /// <summary>
        /// No hay ningún comentario para Cfg_Programa en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Cfg_Programa> Cfg_Programa
        {
            get
            {
                if ((this._Cfg_Programa == null))
                {
                    this._Cfg_Programa = base.CreateQuery<Cfg_Programa>("[Cfg_Programa]");
                }
                return this._Cfg_Programa;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Cfg_Programa> _Cfg_Programa;
        /// <summary>
        /// No hay ningún comentario para configuracion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<configuracion> configuracion
        {
            get
            {
                if ((this._configuracion == null))
                {
                    this._configuracion = base.CreateQuery<configuracion>("[configuracion]");
                }
                return this._configuracion;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<configuracion> _configuracion;
        /// <summary>
        /// No hay ningún comentario para LOGG en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<LOGG> LOGG
        {
            get
            {
                if ((this._LOGG == null))
                {
                    this._LOGG = base.CreateQuery<LOGG>("[LOGG]");
                }
                return this._LOGG;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<LOGG> _LOGG;
        /// <summary>
        /// No hay ningún comentario para vtipoxmoduloes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<vtipoxmodulo> vtipoxmoduloes
        {
            get
            {
                if ((this._vtipoxmoduloes == null))
                {
                    this._vtipoxmoduloes = base.CreateQuery<vtipoxmodulo>("[vtipoxmoduloes]");
                }
                return this._vtipoxmoduloes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<vtipoxmodulo> _vtipoxmoduloes;
        /// <summary>
        /// No hay ningún comentario para vtipoxprogramas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<vtipoxprograma> vtipoxprogramas
        {
            get
            {
                if ((this._vtipoxprogramas == null))
                {
                    this._vtipoxprogramas = base.CreateQuery<vtipoxprograma>("[vtipoxprogramas]");
                }
                return this._vtipoxprogramas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<vtipoxprograma> _vtipoxprogramas;
        /// <summary>
        /// No hay ningún comentario para Cfg_AtiposUsuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_AtiposUsuarios(Cfg_AtiposUsuarios cfg_AtiposUsuarios)
        {
            base.AddObject("Cfg_AtiposUsuarios", cfg_AtiposUsuarios);
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_cModulos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_cModulos(Cfg_cModulos cfg_cModulos)
        {
            base.AddObject("Cfg_cModulos", cfg_cModulos);
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_cModuloxUsuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_cModuloxUsuario(Cfg_cModuloxUsuario cfg_cModuloxUsuario)
        {
            base.AddObject("Cfg_cModuloxUsuario", cfg_cModuloxUsuario);
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_cProgramaxTipoUsuario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_cProgramaxTipoUsuario(Cfg_cProgramaxTipoUsuario cfg_cProgramaxTipoUsuario)
        {
            base.AddObject("Cfg_cProgramaxTipoUsuario", cfg_cProgramaxTipoUsuario);
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_cUsuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_cUsuarios(Cfg_cUsuarios cfg_cUsuarios)
        {
            base.AddObject("Cfg_cUsuarios", cfg_cUsuarios);
        }
        /// <summary>
        /// No hay ningún comentario para Cfg_Programa en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCfg_Programa(Cfg_Programa cfg_Programa)
        {
            base.AddObject("Cfg_Programa", cfg_Programa);
        }
        /// <summary>
        /// No hay ningún comentario para configuracion en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToconfiguracion(configuracion configuracion)
        {
            base.AddObject("configuracion", configuracion);
        }
        /// <summary>
        /// No hay ningún comentario para LOGG en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToLOGG(LOGG lOGG)
        {
            base.AddObject("LOGG", lOGG);
        }
        /// <summary>
        /// No hay ningún comentario para vtipoxmoduloes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTovtipoxmoduloes(vtipoxmodulo vtipoxmodulo)
        {
            base.AddObject("vtipoxmoduloes", vtipoxmodulo);
        }
        /// <summary>
        /// No hay ningún comentario para vtipoxprogramas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTovtipoxprogramas(vtipoxprograma vtipoxprograma)
        {
            base.AddObject("vtipoxprogramas", vtipoxprograma);
        }
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.vtipoxmodulo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// causutipo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="vtipoxmodulo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class vtipoxmodulo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto vtipoxmodulo.
        /// </summary>
        /// <param name="causutipo">Valor inicial de causutipo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static vtipoxmodulo Createvtipoxmodulo(short causutipo)
        {
            vtipoxmodulo vtipoxmodulo = new vtipoxmodulo();
            vtipoxmodulo.causutipo = causutipo;
            return vtipoxmodulo;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad causutipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short causutipo
        {
            get
            {
                return this._causutipo;
            }
            set
            {
                this.OncausutipoChanging(value);
                this.ReportPropertyChanging("causutipo");
                this._causutipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("causutipo");
                this.OncausutipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _causutipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cModulo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> cModulo
        {
            get
            {
                return this._cModulo;
            }
            set
            {
                this.OncModuloChanging(value);
                this.ReportPropertyChanging("cModulo");
                this._cModulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cModulo");
                this.OncModuloChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _cModulo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncModuloChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
    }
    /// <summary>
    /// No hay ningún comentario para adminpaqModel.vtipoxprograma en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// causutipo
    /// cPrograma
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="adminpaqModel", Name="vtipoxprograma")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class vtipoxprograma : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto vtipoxprograma.
        /// </summary>
        /// <param name="causutipo">Valor inicial de causutipo.</param>
        /// <param name="cPrograma">Valor inicial de cPrograma.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static vtipoxprograma Createvtipoxprograma(short causutipo, int cPrograma)
        {
            vtipoxprograma vtipoxprograma = new vtipoxprograma();
            vtipoxprograma.causutipo = causutipo;
            vtipoxprograma.cPrograma = cPrograma;
            return vtipoxprograma;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad causutipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public short causutipo
        {
            get
            {
                return this._causutipo;
            }
            set
            {
                this.OncausutipoChanging(value);
                this.ReportPropertyChanging("causutipo");
                this._causutipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("causutipo");
                this.OncausutipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private short _causutipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanging(short value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncausutipoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad cPrograma en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int cPrograma
        {
            get
            {
                return this._cPrograma;
            }
            set
            {
                this.OncProgramaChanging(value);
                this.ReportPropertyChanging("cPrograma");
                this._cPrograma = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cPrograma");
                this.OncProgramaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _cPrograma;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncProgramaChanged();
    }
}
